# Generated by ./update.sh - do not update manually!
<<<<<<< HEAD
# Last updated: 2025-12-06
||||||| 213fed0310e3
# Last updated: 2025-11-11
=======
# Last updated: 2025-12-19
>>>>>>> master
{ fetchurl, fetchzip }:
{
  aarch64-darwin = {
<<<<<<< HEAD
    version = "1.0.6";
||||||| 213fed0310e3
    version = "1.0.4";
=======
    version = "1.0.7";
>>>>>>> master
    src = fetchurl {
<<<<<<< HEAD
      url = "https://dl.fastmailcdn.com/desktop/production/mac/arm64/Fastmail-1.0.6-arm64-mac.zip";
      hash = "sha512-viKPE0LS4dQQxw9jimEGjAl65uSE7XeAcuoLzq7n4i/BEfNo9QjzOzDMbxhwkGY0Ba92coddwJRXaSdx48fTTw==";
||||||| 213fed0310e3
      url = "https://dl.fastmailcdn.com/desktop/production/mac/arm64/Fastmail-1.0.4-arm64-mac.zip";
      hash = "sha512-DoBG2pY8a1BjNby0/PFAmRnEdMzX3n/JNlGW1/uHvi8lmzDMfEK5F0RAE4bNW08TPnaomjQOMRnqcas/9SecuA==";
=======
      url = "https://dl.fastmailcdn.com/desktop/production/mac/arm64/Fastmail-1.0.7-arm64-mac.zip";
      hash = "sha512-pH6m2BxP/y/A/DaPVNgwmd5HHVbyCVefYhJENyImsKQAKzn8RY9EI/kaybMHlQjv6N0Gmixpskvm0K74k3LUqg==";
>>>>>>> master
    };
  };
  x86_64-linux = {
<<<<<<< HEAD
    version = "1.0.6";
||||||| 213fed0310e3
    version = "1.0.4";
=======
    version = "1.0.7";
>>>>>>> master
    src = fetchurl {
<<<<<<< HEAD
      url = "https://dl.fastmailcdn.com/desktop/production/linux/x64/Fastmail-1.0.6.AppImage";
      hash = "sha512-WKMhy7dLoFUqUkevkZAgxgxpz5jD4O9VVaKDYxQs0jXJVt5GUcIHDJ6aZIJG6jyinAC18NzF3vJnOftw8ZWdmg==";
||||||| 213fed0310e3
      url = "https://dl.fastmailcdn.com/desktop/production/linux/x64/Fastmail-1.0.4.AppImage";
      hash = "sha512-lavGgtrIRiYL4NQEecpppvcTLZCgp54sTDFyVgySzBZmB6bcwCk9Kpjgepjma6iCUtUQYkN5ydtEYLZqTcSw4Q==";
=======
      url = "https://dl.fastmailcdn.com/desktop/production/linux/x64/Fastmail-1.0.7.AppImage";
      hash = "sha512-MFVqBuuruqDVOkK9NC5E60BPJnIHdiL4MhitWqmmUB+NidlBxQbeDeWZu5Pwhh878UXrNvA0mVCgTZAOK7e2Ew==";
>>>>>>> master
    };
  };
}
