# Generated by ./update.sh - do not update manually!
<<<<<<< HEAD
# Last updated: 2025-12-03
||||||| 213fed0310e3
# Last updated: 2025-11-15
=======
# Last updated: 2026-01-09
>>>>>>> master
{ fetchurl }:
let
  any-darwin = {
<<<<<<< HEAD
    version = "6.9.86-2025-12-03";
||||||| 213fed0310e3
    version = "6.9.85-2025-11-14";
=======
    version = "6.9.87-2026-01-08";
>>>>>>> master
    src = fetchurl {
<<<<<<< HEAD
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Mac/QQ_6.9.86_251203_01.dmg";
      hash = "sha256-QzH3XYbARAgNi6WCB/9KZbON9BqpH2eWzYo6n0usCzI=";
||||||| 213fed0310e3
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Mac/QQ_6.9.85_251114_01.dmg";
      hash = "sha256-1m9Kc9ejDZaCCaI/ea/7C1wHz/pX46p9VmlRb8JNv4I=";
=======
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Mac/QQ_6.9.87_260108_01.dmg";
      hash = "sha256-qsRJln44kpR9+muiKzqr0uZ8BEVpRbn/xc1IiQ+xyhk=";
>>>>>>> master
    };
  };
in
{
  aarch64-darwin = any-darwin;
  x86_64-darwin = any-darwin;
  aarch64-linux = {
<<<<<<< HEAD
    version = "3.2.22-2025-12-03";
||||||| 213fed0310e3
    version = "3.2.21-2025-11-14";
=======
    version = "3.2.23-2026-01-08";
>>>>>>> master
    src = fetchurl {
<<<<<<< HEAD
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.22_251203_arm64_01.deb";
      hash = "sha256-3HBpnLkO/an/E876Q0A2mG5JNBafxUdm33DL6KLjeZk=";
||||||| 213fed0310e3
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.21_251114_arm64_01.deb";
      hash = "sha256-g42PDUobpnajM85ykDUVajJKfGsOGqz2EX3pA9a/fY4=";
=======
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.23_260108_arm64_01.deb";
      hash = "sha256-hw7TwOQX6bs6AhwdVlGLwvu6gtHD4YcThPZKt+IZI/c=";
>>>>>>> master
    };
  };
  x86_64-linux = {
<<<<<<< HEAD
    version = "3.2.22-2025-12-03";
||||||| 213fed0310e3
    version = "3.2.21-2025-11-14";
=======
    version = "3.2.23-2026-01-08";
>>>>>>> master
    src = fetchurl {
<<<<<<< HEAD
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.22_251203_amd64_01.deb";
      hash = "sha256-PwBL2yRrMZTSdsY26pbLQKfguBP+pHCVfRMx6AMyvVQ=";
||||||| 213fed0310e3
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.21_251114_amd64_01.deb";
      hash = "sha256-GZyvzkCxDPzrA9TDgO9V+eaTharEGPPsfq6TuOk2KSI=";
=======
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.23_260108_amd64_01.deb";
      hash = "sha256-pCUnGcG+uK3ODaCev8MQzlDHnqVI9czkKVBXZdC/uoQ=";
>>>>>>> master
    };
  };
}
